name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        python -m pip install --upgrade pip
        pip install xarray netcdf4 h5netcdf

    # Add the new steps here
    - name: Generate lagged-ensemble.csv
      run: cat 34Vars/lagged_ensembles/*.csv > frontend/public/lagged-ensemble.csv

    - name: Generate medium-range.csv
      run: python3 bin/convert_netcdfs_to_csv.py frontend/public/medium-range.csv

    - name: Build Next.js Application
      run: |
        cd frontend
        npm run build

    - name: Copy Built Files for Deployment
      run: cp -r frontend/out/* public/

    # Assuming you're using peaceiris/actions-gh-pages for deployment
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Make sure this points to the right directory
